import type { Intent } from "../types.js";

/** Intenções de conversa: saudação, agradecimento, pedir uma pessoa, perguntar se é robô. */
export const conversationIntents: Intent[] = [
  {
    id: "SAUDACAO",
    name: "saudação",
    description: "Oi, bom dia etc. Só vale quando não há outra pergunta junto.",
    keywords: ["oi", "ola", "bom dia", "boa tarde", "boa noite", "e ai", "eai", "opa", "hello", "tudo bem", "oi tudo bem"],
    synonyms: ["saudacao"],
    examples: ["oi tudo bem?", "boa tarde!", "ola, bom dia"],
    priority: 1,
    scope: "geral",
    helper: true,
    response: "Oi! Que alegria receber sua mensagem! 💛\nMe conta: como posso te ajudar?",
    shortResponse: "Oi! 😊 Me conta, como posso te ajudar?",
  },
  {
    id: "AGRADECIMENTO",
    name: "agradecimento",
    description: "Obrigado, ok, combinado.",
    keywords: [
      "obrigado", "obrigada", "muito obrigado", "muito obrigada", "valeu", "agradeco", "ok", "okay", "beleza",
      "combinado", "ta bom", "perfeito", "show", "entendi", "certo", "otimo", "maravilha", "top", "ah ta",
    ],
    synonyms: [],
    negativeKeywords: ["nao entendi"],
    examples: ["obrigada pela ajuda", "ok obrigado", "valeu!"],
    priority: 1,
    scope: "geral",
    helper: true,
    response: "Imagina! 💛 Qualquer dúvida, é só chamar.",
    shortResponse: "Imagina! 💛",
  },
  {
    id: "FALAR_COM_HUMANO",
    name: "falar com alguém da equipe",
    description: "Cliente quer falar com uma pessoa.",
    keywords: [
      "atendente", "falar com atendente", "falar com uma pessoa", "falar com alguem", "atendimento humano",
      "pessoa de verdade", "quero falar com alguem", "alguem da equipe", "falar com o gerente", "gerente",
      "falar com humano", "me liga", "pode me ligar", "telefone de voce", "numero de voce", "reclamacao",
      "quero reclamar", "organizadora", "falar com a organizadora", "falar com a organizadora de festa", "falar com a dona", "falar com o dono",
    ],
    synonyms: ["humano"],
    negativeKeywords: ["voce e", "falando com", "e humano", "e uma pessoa", "e robo"],
    examples: ["quero falar com um atendente", "tem alguem ai para falar comigo?", "posso falar com uma pessoa?"],
    priority: 7,
    scope: "geral",
    response: "Claro! Vou chamar alguém da nossa equipe para falar com você por aqui, combinado? 💛",
    handoff: "Cliente pediu para falar com uma pessoa da equipe.",
  },
  {
    id: "PERGUNTA_ROBO",
    name: "se é um robô",
    description: "Cliente pergunta se está falando com robô/IA. Resposta sempre honesta.",
    keywords: [
      "robo", "e robo", "voce e robo", "voce e um robo", "e um robo", "inteligencia artificial", "chatbot", "bot",
      "e humano", "voce e humano", "e uma pessoa", "voce e uma pessoa", "atendimento automatico", "resposta automatica",
      "falando com uma pessoa", "falando com um robo", "falando com robo", "falando com humano", "e pessoa de verdade",
      "e uma ia", "voce e ia", "e de verdade", "voce e de verdade", "e uma maquina",
    ],
    synonyms: [],
    examples: ["voce e um robo?", "to falando com uma pessoa?", "isso e resposta automatica?"],
    priority: 8,
    scope: "geral",
    response:
      "Sou a assistente virtual da Zind 😊\nSe preferir falar com alguém da equipe, é só me dizer que eu chamo!",
  },
  {
    id: "INFO_INDISPONIVEL",
    name: "um assunto que eu não tenho aqui",
    description: "Assuntos conhecidos que ainda não estão na base: a equipe confirma (nunca inventar).",
    keywords: [
      "estacionamento", "estacionar", "wifi", "wi fi", "promocao", "cupom", "feriado", "trabalhe conosco", "vaga de emprego",
      "curriculo", "excursao", "escola", "grupo grande", "desconto para grupo", "fraldario", "trocador",
      "acessibilidade", "elevador", "lotado", "cheio hoje", "pet", "cachorro", "levar cachorro", "levar pet", "animal", "gato", "achados e perdidos",
      "esqueci", "perdi", "nota fiscal", "vale presente", "gift card", "dia das crianca", "colonia de ferias",
      "idade maxima", "peso maximo", "seguro", "brinquedo quebrado", "machucou", "natal", "ano novo", "pascoa",
      "carnaval", "reveillon", "12 de outubro", "estudante", "desconto para irmao", "irmao", "professor", "idoso",
      "gestante", "gravida", "meia hora", "quanto e meia hora", "valor de meia hora", "preco de meia hora", "pacote mensal", "mensalidade", "plano mensal", "passaporte",
      "pacote de hora", "pacote de 2 hora", "capacidade do salao", "salao vip cabe", "cabe quanta pessoa",
      "perto", "longe", "rampa", "cha de bebe", "cha revelacao", "batizado", "cabe no salao",
      "quanta pessoa cabe no salao", "hora e meia", "1h e meia", "original", "copia do laudo", "laudo digital",
      "pastel", "sorvete", "pizza", "acai", "coxinha", "batata frita", "menu infantil", "vegano", "vegana",
      "sem gluten", "sem lactose", "ticket", "vale alimentacao", "vale refeicao",
    ],
    synonyms: [],
    examples: ["tem estacionamento?", "tem wifi ai?", "abre no feriado?", "voces tem promocao?", "aceitam excursao de escola?"],
    priority: 3,
    scope: "geral",
    noClarify: true,
    response: "Essa informação eu não tenho disponível por aqui, mas nossa equipe pode confirmar para você. 💛",
    handoff: "Pergunta fora da base de respostas.",
  },
];
